In [3]:
current_cache=([1,2,3,],[4,5,6])

In [4]:
len(current_cache)

2

In [5]:
current_cache[0]

[1, 2, 3]

In [6]:
current_cache[1]

[4, 5, 6]

In [1]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
from testCases_v4 import *
from dnn_utils_v2 import sigmoid, sigmoid_backward,relu, relu_backward

In [18]:
da=np.array([[1,2]])#one row and inside two columns

In [19]:
da.shape

(1, 2)

In [21]:
sum=da.sum(axis=1)

In [22]:
sum.shape

(1,)

In [23]:
sum.reshape(1,1)

array([[3]])

In [3]:
a=np.random.randn(3,3)

In [4]:
b=np.random.randn(3,3)

In [5]:
a

array([[-0.5827282 , -0.16827656, -0.25112882],
       [ 1.55809341, -0.65867993,  0.66814055],
       [-0.01241656, -1.06207812, -0.69593832]])

In [6]:
b

array([[-0.88211895, -1.07504784, -0.85238109],
       [ 0.88814146,  0.45143126, -0.55704123],
       [-1.1638119 , -1.08053263, -0.36247422]])

In [8]:
a_dot_b=np.dot(a,b)

In [9]:
a_dot_b

array([[ 0.65684891,  0.82184828,  0.68147121],
       [-2.73701459, -2.69432134, -1.20336121],
       [-0.12238142,  0.2858772 ,  0.85446465]])

In [10]:
np.sum(a_dot_b)

-3.4565683215181546

In [11]:
c=np.array([[1,1,1],
           [2,2,2],
           [3,3,3]])

In [13]:
d=np.ones((3,3))

In [14]:
np.dot(c,d)

array([[3., 3., 3.],
       [6., 6., 6.],
       [9., 9., 9.]])

In [15]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
np.multiply(c,d)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [3]:
np.random.seed(1)
A_prev=np.random.randn(10,4,4,3)
W=np.random.randn(2,2,3,8)
b=np.random.randn(1,1,1,8)

In [4]:
A_prev

array([[[[ 1.62434536e+00, -6.11756414e-01, -5.28171752e-01],
         [-1.07296862e+00,  8.65407629e-01, -2.30153870e+00],
         [ 1.74481176e+00, -7.61206901e-01,  3.19039096e-01],
         [-2.49370375e-01,  1.46210794e+00, -2.06014071e+00]],

        [[-3.22417204e-01, -3.84054355e-01,  1.13376944e+00],
         [-1.09989127e+00, -1.72428208e-01, -8.77858418e-01],
         [ 4.22137467e-02,  5.82815214e-01, -1.10061918e+00],
         [ 1.14472371e+00,  9.01590721e-01,  5.02494339e-01]],

        [[ 9.00855949e-01, -6.83727859e-01, -1.22890226e-01],
         [-9.35769434e-01, -2.67888080e-01,  5.30355467e-01],
         [-6.91660752e-01, -3.96753527e-01, -6.87172700e-01],
         [-8.45205641e-01, -6.71246131e-01, -1.26645989e-02]],

        [[-1.11731035e+00,  2.34415698e-01,  1.65980218e+00],
         [ 7.42044161e-01, -1.91835552e-01, -8.87628964e-01],
         [-7.47158294e-01,  1.69245460e+00,  5.08077548e-02],
         [-6.36995647e-01,  1.90915485e-01,  2.10025514e+00]]],


In [5]:
A_prev.shape

(10, 4, 4, 3)

A1=A_prev[:,:,:,1]

In [9]:
A1

array([[[-5.28171752e-01, -2.30153870e+00,  3.19039096e-01,
         -2.06014071e+00],
        [ 1.13376944e+00, -8.77858418e-01, -1.10061918e+00,
          5.02494339e-01],
        [-1.22890226e-01,  5.30355467e-01, -6.87172700e-01,
         -1.26645989e-02],
        [ 1.65980218e+00, -8.87628964e-01,  5.08077548e-02,
          2.10025514e+00]],

       [[ 3.00170320e-01, -3.49342722e-01,  8.38983414e-01,
          8.85141164e-01],
        [ 5.12929820e-01, -7.55717130e-02,  2.18557541e+00,
         -5.04465863e-01],
        [ 3.15634947e-01,  8.27974643e-01, -2.22328143e-01,
          4.10051647e-01],
        [-6.70662286e-01,  1.12948391e+00, -3.75284950e-01,
          7.73400683e-02]],

       [[-6.20000844e-01,  1.22450770e+00, -1.09491185e+00,
         -9.53700602e-01],
        [-1.37311732e+00, -8.59515941e-01, -3.86955093e-02,
          4.08900538e-01],
        [ 1.27375593e+00,  1.23616403e+00, -1.19926803e+00,
         -6.03920628e-01],
        [ 7.92806866e-01, -1.14434139e+

In [9]:
A1.shape

(4, 4, 3)

In [10]:
W

array([[[[ 0.5154138 , -1.11487105, -0.76730983,  0.67457071,
           1.46089238,  0.5924728 ,  1.19783084,  1.70459417],
         [ 1.04008915, -0.91844004, -0.10534471,  0.63019567,
          -0.4148469 ,  0.45194604, -1.57915629, -0.82862798],
         [ 0.52887975, -2.23708651, -1.1077125 , -0.01771832,
          -1.71939447,  0.057121  , -0.79954749, -0.2915946 ]],

        [[-0.25898285,  0.1892932 , -0.56378873,  0.08968641,
          -0.6011568 ,  0.55607351,  1.69380911,  0.19686978],
         [ 0.16986926, -1.16400797,  0.69336623, -0.75806733,
          -0.8088472 ,  0.55743945,  0.18103874,  1.10717545],
         [ 1.44287693, -0.53968156,  0.12837699,  1.76041518,
           0.96653925,  0.71304905,  1.30620607, -0.60460297]]],


       [[[ 0.63658341,  1.40925339,  1.62091229, -0.80618482,
          -0.25167421,  0.38271517, -0.28899734, -0.39181624],
         [ 0.68400133, -0.35340998, -1.78791289,  0.36184732,
          -0.42449279, -0.73153098, -1.56573815,  1.01382

In [11]:
W.shape

(2, 2, 3, 8)

In [15]:
w11=W[1][1]

In [16]:
w11

array([[ 1.01120706, -1.47656266, -0.14319575,  1.03298378, -0.22241403,
         1.47016034, -0.87000822,  0.36919047],
       [ 0.85328219, -0.13971173,  1.38631426,  0.54812958, -1.63744959,
         3.9586027 ,  0.64864364,  0.10734329],
       [-1.39881282,  0.08176782, -0.45994283,  0.64435367,  0.37167029,
         1.85300949,  0.14225137,  0.51350548]])

In [13]:
W.shape

(2, 2, 3, 8)

In [16]:
W[:,:,:,7]

array([[[ 1.70459417, -0.82862798, -0.2915946 ],
        [ 0.19686978,  1.10717545, -0.60460297]],

       [[-0.39181624,  1.01382247, -1.51045638],
        [ 0.36919047,  0.10734329,  0.51350548]]])

In [11]:
W

array([[[[ 0.5154138 , -1.11487105, -0.76730983,  0.67457071,
           1.46089238,  0.5924728 ,  1.19783084,  1.70459417],
         [ 1.04008915, -0.91844004, -0.10534471,  0.63019567,
          -0.4148469 ,  0.45194604, -1.57915629, -0.82862798],
         [ 0.52887975, -2.23708651, -1.1077125 , -0.01771832,
          -1.71939447,  0.057121  , -0.79954749, -0.2915946 ]],

        [[-0.25898285,  0.1892932 , -0.56378873,  0.08968641,
          -0.6011568 ,  0.55607351,  1.69380911,  0.19686978],
         [ 0.16986926, -1.16400797,  0.69336623, -0.75806733,
          -0.8088472 ,  0.55743945,  0.18103874,  1.10717545],
         [ 1.44287693, -0.53968156,  0.12837699,  1.76041518,
           0.96653925,  0.71304905,  1.30620607, -0.60460297]]],


       [[[ 0.63658341,  1.40925339,  1.62091229, -0.80618482,
          -0.25167421,  0.38271517, -0.28899734, -0.39181624],
         [ 0.68400133, -0.35340998, -1.78791289,  0.36184732,
          -0.42449279, -0.73153098, -1.56573815,  1.01382

In [1]:
3%(40/10)

3.0